---
title: "Appendix"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{appendix}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(adatutoR)
```

# Appendix

First, we need to make sure that the appendix itself is reproducible from the
code in the vignette. So we add everything to the appendix that is necessary to
make it a standalone.

```{r}
# Variables of interest
voi <- c("pid","eid", "power.o", "effect_size.o", "n.o", "log_p.o", "replicated")
# Outcome (classification task) 
target <- "replicated"
# Predictors 
features <- c("power.o", "effect_size.o", "n.o", "log_p.o")
# Note: No missing values 
df <- altmext[,voi]
```


```{r}
# Reproducibility
set.seed(112)
# Split proportion
sprop <- 0.7

# Number of effects 
n_effect <- nrow(df)

# Number of training samples
n_train <- round(n_effect * sprop)

# Training index
train_idx <- sample(seq_len(n_effect), n_train)

# Training and testing set 
train <- df[train_idx, ]
test  <- df[-train_idx, ] 

# Feature matrices
X_train <- train[,features] 
X_test <- test[,features] 

# Target vectors 
y_train <- train[,target]
y_test <- test[,target]
```

# Figure 1 

```{r}
# Extract only two features to reduce run-time 
subfeat <- c("power.o", "n.o")
subdf <-  train[,union(subfeat, target)]
# Number of classes
k <- length(unique(subdf$replicated))
# Range(s) as list
rng <- lapply(subdf[,subfeat], range, na.rm = TRUE)
# Grid resolution
resolution <- 1e3 
# Colors
col1 <- "cornflowerblue" ; col2 <- "ivory4"
# Transparency
alpha.f <- 0.03
col1_transp <- adjustcolor(col1, alpha.f)
col2_transp <- adjustcolor(col2, alpha.f) 
# First feature sequence
x1_seq <- seq(rng$power.o[1], rng$power.o[2], length.out = resolution)
# Second feature sequence
x2_seq <- seq(rng$n.o[1], rng$n.o[2], length.out = resolution)
# Make grid from sequences
grid <- expand.grid("power.o" = x1_seq, "n.o" = x2_seq)
# Maybe as comparison the decision boundaries from a GLM?
mdl <- glm(replicated ~., data = subdf, family=binomial(link='logit'))
# Change class attribute
class(mdl) <- c("lr", class(mdl))
# Predicted probability of replication success
y_prob <- predict(mdl, grid, type = "response")
# If p > 0.5 "replicated", else "not replicated"
y_pred <- factor(as.integer(y_prob > 0.5))
# Contour matrix
z_mat <- matrix(as.integer(y_pred), nrow = resolution)
# "no" means "not replicated", "yes" means "replicated"
symbol_colors <- ifelse(y_train == "failure", col1, col2)
# "0" means "not replicated", "1" means "replicated"
grid_colors <- ifelse(y_pred == 0, col1_transp, col2_transp) 
# Plot the features
plot(NULL, xlim = range(x1_seq), ylim = range(x2_seq), 
     xlab = "power.o", ylab = "n.o", main = "Decision Boundary")
mtext("Bernoulli Logit Generalized Linear Model")
points(grid, col = grid_colors, pch = ".")
points(subdf[,subfeat], col = symbol_colors, pch = as.integer(y_train) + 15, )
contour(x1_seq, x2_seq, z_mat, add = TRUE, drawlabels = FALSE, lwd = 2, 
        col = "black", levels = (1:(k-1))+.5)
legend("topleft", c("success", "failure") , pch = c(17,16), 
       col = c(col2, col1), cex=0.7)
```
